---
application:
  name: "directus-api"
  project: "Agrigates"
  organization: "QoveryCommunity"
databases:
- type: "POSTGRESQL"
  name: "directus"
  version: "11"
routers:
- name: "main-directus-api"
  routes:
  - application_name: "directus-api"
    paths:
    - "/*"
